src/mbr: use #pragma pack instead of __attribute__((packed))
Even with commit 204b322243a4 src/mbr: fix struct mbr packing, we get
errors from gcc:
  src/mbr.c: In function ‘r_mbr_switch_get_inactive_partition’:
  src/mbr.c:291:53: error: taking address of packed member of ‘struct mbr’ may
  result in an unaligned pointer value [-Werror=address-of-packed-member]
    291 |  res = is_region_free(region_start, region_size, mbr.partition_table,
        |                                                  ~~~^~~~~~~~~~~~~~~~
  src/mbr.c:265:30: error: unused variable ‘boot_part’ [-Werror=unused-variable]
    265 |  struct partition_tbl_entry *boot_part;
        |                              ^~~~~~~~~
  src/mbr.c: In function ‘r_mbr_switch_set_boot_partition’:
  src/mbr.c:418:14: error: taking address of packed member of ‘struct mbr’ may
  result in an unaligned pointer value [-Werror=address-of-packed-member]
    418 |  boot_part = &mbr.partition_table[BOOT_PARTITION_ENTRY];
        |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

We can avoid this by marking the involved structs with #prackma pack, which
will cause generation of code which handles unaligned data without warning
about it.

As this code is not performance relevant, we can accept the minor slowdown
(which only occurs on architectures like ARMv5 without unaligned access support
anyway).

Signed-off-by: Jan Luebbe <jlu@pengutronix.de>