src/config_file: fix uninitialized local
The local variable group in the while loop may be free'd uninitialized
if the following if statement is reached.

	if (!slot->status) {
		continue;
	}

The variable is declared right before that statement and it is
initialized right after.

Fixes:

	In file included from /usr/include/glib-2.0/glib.h:114,
	                 from src/config_file.c:1:
	src/config_file.c: In function ‘save_slot_status’:
	/usr/include/glib-2.0/glib/glib-autocleanups.h:28:3: error: ‘group’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
	   28 |   g_free (*pp);
	      |   ^~~~~~~~~~~~
	src/config_file.c:905:21: note: ‘group’ was declared here
	  905 |   g_autofree gchar *group;
	      |                     ^~~~~
	cc1: all warnings being treated as errors

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>