suppress -Werror=address-of-packed-member warning/error
Recent addition of `packed` attribute to the `mbr` struct in #453 has broken
x86 builds by introducing a _perceived_ potential alignment violation to which
GCC objects by issuing these warnings:

```
src/mbr.c: In function ‘r_mbr_switch_get_inactive_partition’:
src/mbr.c:291:53: error: taking address of packed member of ‘struct mbr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  291 |  res = is_region_free(region_start, region_size, mbr.partition_table,
      |                                                  ~~~^~~~~~~~~~~~~~~~
src/mbr.c:265:30: error: unused variable ‘boot_part’ [-Werror=unused-variable]
  265 |  struct partition_tbl_entry *boot_part;
      |                              ^~~~~~~~~
src/mbr.c: In function ‘r_mbr_switch_set_boot_partition’:
src/mbr.c:418:14: error: taking address of packed member of ‘struct mbr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  418 |  boot_part = &mbr.partition_table[BOOT_PARTITION_ENTRY];
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```

In order to tone GCC (or Clang) down, provide assurance that the compiler is safe
to assume the MBR partition table entries are aligned on 16-bit boundaries.

Signed-off-by: Roman Beranek <roman.beranek@prusa3d.com>