src/dm.c: add missing string.h include
memset() is defined in string.h but string.h not explicitly included.

Leads to compilation errors with older toolchains:

| src/dm.c:15:2: error: implicit declaration of function 'memset' [-Werror=implicit-function-declaration]
|   memset(header, 0, sizeof(*header));

Signed-off-by: Enrico Joerns <ejo@pengutronix.de>