src/mbr: fix struct mbr packing
This previous approach caused warnings, altough the layout is exactly
was we need it:
  src/mbr.c:28:10: error: packed attribute causes inefficient alignment
  for ‘disk_signature’ [-Werror=attributes]
Adding a aligned(4) or even aligned(1) attribute does not silence the
warning.

Signed-off-by: Jan Luebbe <jlu@pengutronix.de>